#!/bin/bash

set -x

tagNumber=`git branch | grep -e "^*" | cut -d' ' -f 2`
echo "tag number:"
echo "$tagNumber"

git checkout master &&
git merge "$tagNumber" &&
git add .  &&
git commit -m 'autocommit';
git push origin master &&
git checkout "$tagNumber" &&

echo "ok deployed static.pi"

